force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Used to hold information about the Project Milestone.</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the milestone</description>
    <inlineHelpText>The current status of the milestone</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TodoItem__c/TodoItem__c.object-meta.xml
<CustomObject>
    <description>Items of a Milestone to be done.</description>
    <label>To-do item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-do items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TodoItem__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>The milestone to which this item refers.</description>
    <inlineHelpText>The milestone to which this item refers.</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-do items</relationshipLabel>
    <relationshipName>TodoItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TodoItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the item</description>
    <inlineHelpText>The current status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <description>Status of a Project, Milestone or To-do item</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TodoItemTriggerHandler.cls
public with sharing class TodoItemTriggerHandler {
    
    public static void updateMilestoneStatus(List<TodoItem__c> listItems, Map<Id,TodoItem__c> oldMap){
        List<TodoItem__c> listItemsToCheck = new List<TodoItem__c>();
        List<Milestone__c> listMilestonesToUpdate = new List<Milestone__c>();
        Set<String> setIdsMilestones = new Set<String>();
        Set<String> setIdsItemsDisconsider = new Set<String>();
        Boolean hasCompleted = false;
        Boolean hasStarted = false;
        Boolean hasNotInitiated = false;
        Milestone__c milestoneToUpdate = new Milestone__c();
        
        for(TodoItem__c item : listItems){
            //Check the item only if the status was changed, or the item is new, or the item was deleted or the item was undeleted
            if(oldMap == null || item.Status__c != oldMap.get(item.id).Status__c){
                listItemsToCheck.add(item);
                setIdsMilestones.add(item.Milestone__c);
                if(Trigger.isDelete) setIdsItemsDisconsider.add(item.id);
            }
        }
        
        if(listItemsToCheck.size() > 0){
            for(Milestone__c milestone : [SELECT Id, Status__c, (SELECT Id, Status__c FROM TodoItems__r WHERE Id NOT IN :setIdsItemsDisconsider) FROM Milestone__c WHERE Id IN :setIdsMilestones WITH SECURITY_ENFORCED]){
                hasCompleted = false;
                hasStarted = false;
                hasNotInitiated = false;
                milestoneToUpdate = new Milestone__c(id = milestone.id);
                
                for(TodoItem__c item : milestone.TodoItems__r){
                    if(item.Status__c == 'Complete') hasCompleted = true;
                    else if(item.Status__c == 'In Progress') hasStarted = true;
                    else hasNotInitiated = true;
                }
                
                if(hasCompleted && !hasStarted && !hasNotInitiated) milestoneToUpdate.Status__c = 'Complete';
                else if(hasStarted || hasCompleted) milestoneToUpdate.Status__c = 'In Progress';
                else milestoneToUpdate.Status__c = 'Not Started	';
                                
                //There is no need to update the Milestone if the Status is still correct
                if(milestone.Status__c != milestoneToUpdate.Status__c) listMilestonesToUpdate.add(milestoneToUpdate);
            }
            
            if(listMilestonesToUpdate.size() > 0) UPDATE as USER listMilestonesToUpdate;
        }
    }

}