force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Used to hold information about the Project Milestone.</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project to which this milestone refers.</description>
    <inlineHelpText>The project to which this milestone refers.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the milestone</description>
    <inlineHelpText>The current status of the milestone</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the Project</description>
    <inlineHelpText>The current status of the Project</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TodoItem__c/TodoItem__c.object-meta.xml
<CustomObject>
    <description>Items of a Milestone to be done.</description>
    <label>To-do item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-do items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TodoItem__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>The milestone to which this item refers.</description>
    <inlineHelpText>The milestone to which this item refers.</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-do items</relationshipLabel>
    <relationshipName>TodoItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TodoItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the item</description>
    <inlineHelpText>The current status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <description>Status of a Project, Milestone or To-do item</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectWithMilestonesAndItemsController.cls
public with sharing class ProjectWithMilestonesAndItemsController {
    
    @AuraEnabled
    public static String saveRecords(Project__c project, List<Milestone> listMilestones){
        Savepoint sp = Database.setSavepoint();

        try {
            System.debug('project:'+project);
            INSERT as USER project;

            Integer index = 0;
            Map<Integer,List<TodoItem__c>> mapItemsByMilestoneIndex = new Map<Integer,List<TodoItem__c>>();
            List<Milestone__c> listNewMilestones = new List<Milestone__c>();
            List<TodoItem__c> listNewItems = new List<TodoItem__c>();

            for(Milestone miles : listMilestones){
                listNewMilestones.add(new Milestone__c(Status__c = miles.Status, Name = miles.Name, Project__c = project.Id));
                mapItemsByMilestoneIndex.put(index,miles.listItems);
                index ++;
            }

            INSERT as USER listNewMilestones;

            for(integer milestoneIndex : mapItemsByMilestoneIndex.keySet()){
                if(mapItemsByMilestoneIndex.get(milestoneIndex) == null) continue;
                 
                for(TodoItem__c item : mapItemsByMilestoneIndex.get(milestoneIndex)){
                    item.Milestone__c = listNewMilestones[milestoneIndex].Id;
                    listNewItems.add(item);
                }
            }

            INSERT as USER listNewItems;

            return project.Id;
        } catch (Exception e) {
            System.debug('Error: '+e.getMessage() + ' Cause: '+e.getCause() + 'ST: '+e.getStackTraceString());
            Database.rollback(sp); 
            throw new AuraHandledException(e.getMessage());
        }
    }

    @TestVisible
    private class Milestone{
        @AuraEnabled public String Name {get;set;}
        @AuraEnabled public String Status {get;set;}
        @AuraEnabled public List<TodoItem__c> listItems {get;set;}
    }

}