force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Used to hold information about the Project Milestone.</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project to which this milestone refers.</description>
    <inlineHelpText>The project to which this milestone refers.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the milestone</description>
    <inlineHelpText>The current status of the milestone</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the Project</description>
    <inlineHelpText>The current status of the Project</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TodoItem__c/TodoItem__c.object-meta.xml
<CustomObject>
    <description>Items of a Milestone to be done.</description>
    <label>To-do item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-do items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TodoItem__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>The milestone to which this item refers.</description>
    <inlineHelpText>The milestone to which this item refers.</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-do items</relationshipLabel>
    <relationshipName>TodoItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TodoItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the item</description>
    <inlineHelpText>The current status of the item</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <description>Status of a Project, Milestone or To-do item</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectWithMilestonesAndItemsCtrlTest.cls
@isTest
public class ProjectWithMilestonesAndItemsCtrlTest {

    @isTest
    public static void saveRecordsTest(){
        String projectJson = '{"sobjectType":"Project__c","Name":"project test","Status__c":"Not Started"}';
        String milestoneJson = '[{"Name":"milestone 1","Status":"Not Started","key":0,"listItems":[{"sobjectType":"TodoItem__c","Name":"item 11","Status__c":"Not Started","parentIndex":"0","key":0},{"sobjectType":"TodoItem__c","Name":"item 12","Status__c":"Not Started","parentIndex":"0","key":1}]},{"Name":"milestone 2","Status":"Not Started","key":1,"listItems":[{"sobjectType":"TodoItem__c","Name":"21","Status__c":"Not Started","parentIndex":"1","key":0},{"sobjectType":"TodoItem__c","Name":"22","Status__c":"Not Started","parentIndex":"1","key":1}]}]';
        
        Project__c project = (Project__c) JSON.deserialize(projectJson, Project__c.class);
        List<ProjectWithMilestonesAndItemsController.Milestone> listMilestones = (List<ProjectWithMilestonesAndItemsController.Milestone>) JSON.deserialize(milestoneJson, List<ProjectWithMilestonesAndItemsController.Milestone>.class);
        
        Test.startTest();
        ProjectWithMilestonesAndItemsController.saveRecords(project, listMilestones);
        
        Project__c proj = [SELECT Id, Status__c FROM Project__c];
        Assert.areEqual(project.Id, proj.Id, 'Check if the Project record was created');
        
        List<Milestone__c> listMilestonesCreated = [SELECT Id FROM Milestone__c];
        Assert.areEqual(listMilestonesCreated.size(), 2, 'Check if 2 Milestones were created');
        
        List<TodoItem__c> listItemsCreated = [SELECT Id FROM TodoItem__c];
        Assert.areEqual(listItemsCreated.size(), 4, 'Check if 4 TodoItems were created');
        Test.stopTest();
    }
    
}