force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Used to hold information about the Project Milestone.</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project to which this milestone refers.</description>
    <inlineHelpText>The project to which this milestone refers.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the milestone</description>
    <inlineHelpText>The current status of the milestone</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the Project</description>
    <inlineHelpText>The current status of the Project</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <description>Status of a Project, Milestone or To-do item</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MilestoneTriggerHandler.cls
public class MilestoneTriggerHandler {
    
    public static void updateProjectStatus(List<Milestone__c> listMilestones, Map<Id,Milestone__c> oldMap){
        List<Milestone__c> listMilestonesToCheck = new List<Milestone__c>();
        List<Project__c> listProjectsToUpdate = new List<Project__c>();
        Set<String> setIdsProjects = new Set<String>();
        Set<String> setIdsMilestonesDisconsider = new Set<String>();
        Boolean hasCompleted = false;
        Boolean hasStarted = false;
        Boolean hasNotInitiated = false;
        Project__c projectToUpdate = new Project__c();
        
        for(Milestone__c milestone : listMilestones){
            //Check the milestone only if the status was changed, or the milestone is new, or the milestone was deleted or the milestone was undeleted
            if(oldMap == null || milestone.Status__c != oldMap.get(milestone.id).Status__c){
                listMilestonesToCheck.add(milestone);
                setIdsProjects.add(milestone.Project__c);
                if(Trigger.isDelete) setIdsMilestonesDisconsider.add(milestone.id);
            }
        }
        
        if(listMilestonesToCheck.size() > 0){
            for(Project__c project : [SELECT Id, Status__c, (SELECT Id, Status__c FROM Milestones__r WHERE Id NOT IN :setIdsMilestonesDisconsider) FROM Project__c WHERE Id IN :setIdsProjects WITH SECURITY_ENFORCED]){
                hasCompleted = false;
                hasStarted = false;
                hasNotInitiated = false;
                projectToUpdate = new Project__c(id = project.id);
                
                for(Milestone__c milestone : project.Milestones__r){
                    if(milestone.Status__c == 'Complete') hasCompleted = true;
                    else if(milestone.Status__c == 'In Progress') hasStarted = true;
                    else hasNotInitiated = true;
                }
                
                if(hasCompleted && !hasStarted && !hasNotInitiated) projectToUpdate.Status__c = 'Complete';
                else if(hasStarted || hasCompleted) projectToUpdate.Status__c = 'In Progress';
                else projectToUpdate.Status__c = 'Not Started	';
                
                //There is no need to update the Project if the Status is still correct
                if(project.Status__c != projectToUpdate.Status__c) listProjectsToUpdate.add(projectToUpdate);
            }
            
            if(listProjectsToUpdate.size() > 0) UPDATE as USER listProjectsToUpdate;
        }
    }
    
}